# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\chart_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChartSelector(object):
    def setupUi(self, ChartSelector):
        ChartSelector.setObjectName("ChartSelector")
        ChartSelector.resize(1070, 577)
        self.centralwidget = QtWidgets.QWidget(ChartSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(750, 280, 151, 62))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Chart_Selector = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Chart_Selector.setContentsMargins(0, 0, 0, 0)
        self.Chart_Selector.setObjectName("Chart_Selector")
        self.bar_chart = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bar_chart.setObjectName("bar_chart")
        self.Chart_Selector.addWidget(self.bar_chart)
        self.line_chart = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.line_chart.setObjectName("line_chart")
        self.Chart_Selector.addWidget(self.line_chart)
        self.pie_chart = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.pie_chart.setObjectName("pie_chart")
        self.Chart_Selector.addWidget(self.pie_chart)
        ChartSelector.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChartSelector)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        ChartSelector.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChartSelector)
        self.statusbar.setObjectName("statusbar")
        ChartSelector.setStatusBar(self.statusbar)

        self.retranslateUi(ChartSelector)
        QtCore.QMetaObject.connectSlotsByName(ChartSelector)

    def retranslateUi(self, ChartSelector):
        _translate = QtCore.QCoreApplication.translate
        ChartSelector.setWindowTitle(_translate("ChartSelector", "MainWindow"))
        self.bar_chart.setText(_translate("ChartSelector", "条形图"))
        self.line_chart.setText(_translate("ChartSelector", "折线图"))
        self.pie_chart.setText(_translate("ChartSelector", "饼状图"))
