# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\chat_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(928, 655)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.background = QtWidgets.QFrame(Main)
        self.background.setStyleSheet("QFrame{background-color:rgb(86, 62, 206);\n"
"border:none;\n"
"border-radius:12px;\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.main_window = QtWidgets.QFrame(self.background)
        self.main_window.setStyleSheet("*{\n"
"    background-color: rgb(251, 246, 252);\n"
"border:none;\n"
"border-radius:12px;\n"
"}\n"
"QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    height:0px;\n"
"    background:rgba(125,125,125,30%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    height:0px;\n"
"    background:rgba(125,125,125,100%);\n"
"    min-width:20;\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,30%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,100%);\n"
"    border-radius:4px;\n"
"    min-height:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"")
        self.main_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_window.setObjectName("main_window")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_window)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left = QtWidgets.QFrame(self.main_window)
        self.left.setMaximumSize(QtCore.QSize(252, 99999))
        self.left.setStyleSheet("QFrame{\n"
"    background-color: rgb(108, 82, 253);\n"
"border-radius:14px;\n"
"}")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.left)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.left)
        self.frame_5.setMinimumSize(QtCore.QSize(171, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(204, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(24, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addWidget(self.frame_5)
        self.horizontalLayout_2.addWidget(self.left)
        self.right = QtWidgets.QFrame(self.main_window)
        self.right.setMinimumSize(QtCore.QSize(700, 485))
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.right)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.page)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_15)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 664, 550))
        self.scrollAreaWidgetContents_5.setStyleSheet("            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F386A6;\n"
"                width: 2px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #F386A6;\n"
"                min-height: 20px;\n"
"            }\n"
"            QScrollBar::add-line:vertical {\n"
"                background: none;\n"
"                height: 0px;\n"
"                subcontrol-position: bottom;\n"
"                subcontrol-origin: margin;\n"
"            }\n"
"            QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"                height: 0px;\n"
"                subcontrol-position: top;\n"
"                subcontrol-origin: margin;\n"
"            }\n"
"            QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.listWidget_5 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_5)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 0, 664, 541))
        self.listWidget_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget_5.setStyleSheet("selection-background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"gridline-color: rgba(255, 255, 255, 0);\n"
"")
        self.listWidget_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_5.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget_5.setProperty("isWrapping", False)
        self.listWidget_5.setObjectName("listWidget_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_3.setStyleSheet("font-family:\"微软雅黑\";")
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_8.addWidget(self.lineEdit_3)
        self.frame_18 = QtWidgets.QFrame(self.frame_15)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setStyleSheet("font-family:\"微软雅黑\";")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushbutton = QtWidgets.QPushButton(self.frame_19)
        self.pushbutton.setStyleSheet("font-family:\"微软雅黑\";")
        self.pushbutton.setObjectName("pushbutton")
        self.horizontalLayout_11.addWidget(self.pushbutton)
        self.label = QtWidgets.QLabel(self.frame_19)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.previous_message_button = QtWidgets.QPushButton(self.frame_19)
        self.previous_message_button.setStyleSheet("QPushButton {\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.previous_message_button.setObjectName("previous_message_button")
        self.horizontalLayout_11.addWidget(self.previous_message_button)
        self.next_message_button = QtWidgets.QPushButton(self.frame_19)
        self.next_message_button.setStyleSheet("QPushButton {\n"
"    font-family: \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(225, 225, 225);\n"
"}")
        self.next_message_button.setObjectName("next_message_button")
        self.horizontalLayout_11.addWidget(self.next_message_button)
        self.horizontalLayout_10.addWidget(self.frame_19)
        self.verticalLayout_8.addWidget(self.frame_18)
        self.horizontalLayout_12.addWidget(self.frame_15)
        self.horizontalLayout_12.setStretch(0, 3)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.verticalLayout_9.setStretch(0, 5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.right)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_8.addWidget(self.main_window)
        self.verticalLayout_2.addWidget(self.background)

        self.retranslateUi(Main)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.lineEdit_3.setText(_translate("Main", "你需要的文件有A,B,C"))
        self.lineEdit_3.setPlaceholderText(_translate("Main", "Type yout message ..."))
        self.pushbutton.setText(_translate("Main", "段落一"))
        self.label.setText(_translate("Main", "                                                                                                                                  "))
        self.previous_message_button.setText(_translate("Main", "上一条"))
        self.next_message_button.setText(_translate("Main", "下一条"))
