# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\click_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modules.click_qlabel import ClickQLabel

class Ui_ClickLabel(object):
    def setupUi(self, ClickLabel):
        ClickLabel.setObjectName("ClickLabel")
        ClickLabel.resize(1070, 577)
        self.centralwidget = QtWidgets.QWidget(ClickLabel)
        self.centralwidget.setObjectName("centralwidget")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setGeometry(QtCore.QRect(0, 0, 851, 391))
        self.TabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border-top: 2px solid rgba(0, 0, 0, 1); /* 黑色 */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 12px;\n"
"    font-weight: 500;\n"
"    padding: 10px 25px; /* 增加内边距 */\n"
"    border-bottom: none;\n"
"    min-width: 45px;\n"
"   \n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgba(123,190,254, 1); /* 淡蓝色 */\n"
"    border-bottom: 2px solid rgba(123,190,254, 1); /* 淡蓝色 */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-bottom: 2px;\n"
"}\n"
"")
        self.TabWidget.setObjectName("TabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.t1_text_label = ClickQLabel(self.tab_1)
        self.t1_text_label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.t1_text_label.setStyleSheet("font-family: \"Microsoft YaHei\";")
        self.t1_text_label.setObjectName("t1_text_label")
        self.t1_switch_t2_label = ClickQLabel(self.tab_1)
        self.t1_switch_t2_label.setGeometry(QtCore.QRect(90, 90, 171, 131))
        self.t1_switch_t2_label.setStyleSheet("/* 初始样式 */\n"
"QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"    background-color: rgba(123, 190, 254, 1); /* 淡蓝色 */\n"
"    border: 2px solid rgba(0,0,0, 1); /*黑边*/\n"
"}\n"
"\n"
"/* 悬停样式 */\n"
"QLabel::hover {\n"
"    background-color: rgba(80, 100, 150, 1); /* 深蓝色 */\n"
"    color: rgba(220, 220, 220, 1); /* 字体颜色 */\n"
"    border: 2px solid rgba(255,0,0, 1); /* 白色边框 */\n"
"}\n"
"")
        self.t1_switch_t2_label.setObjectName("t1_switch_t2_label")
        self.TabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.t2_text_label = ClickQLabel(self.tab_2)
        self.t2_text_label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.t2_text_label.setStyleSheet("font-family: \"Microsoft YaHei\";\n"
"")
        self.t2_text_label.setObjectName("t2_text_label")
        self.t2_switch_t1_label = ClickQLabel(self.tab_2)
        self.t2_switch_t1_label.setGeometry(QtCore.QRect(0, 80, 171, 131))
        self.t2_switch_t1_label.setStyleSheet("/* 初始样式 */\n"
"QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"    background-color: rgba(123, 190, 254, 1); /* 淡蓝色 */\n"
"    border: 2px solid rgba(0,0,0, 1); /*黑边*/\n"
"}\n"
"\n"
"/* 悬停样式 */\n"
"QLabel::hover {\n"
"    background-color: rgba(80, 100, 150, 1); /* 深蓝色 */\n"
"    color: rgba(220, 220, 220, 1); /* 字体颜色 */\n"
"    border: 2px solid rgba(255,0,0, 1); /* 白色边框 */\n"
"}\n"
"")
        self.t2_switch_t1_label.setObjectName("t2_switch_t1_label")
        self.TabWidget.addTab(self.tab_2, "")
        ClickLabel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClickLabel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 23))
        self.menubar.setObjectName("menubar")
        ClickLabel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClickLabel)
        self.statusbar.setObjectName("statusbar")
        ClickLabel.setStatusBar(self.statusbar)

        self.retranslateUi(ClickLabel)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClickLabel)

    def retranslateUi(self, ClickLabel):
        _translate = QtCore.QCoreApplication.translate
        ClickLabel.setWindowTitle(_translate("ClickLabel", "MainWindow"))
        self.t1_text_label.setText(_translate("ClickLabel", "这里是tab1"))
        self.t1_switch_t2_label.setText(_translate("ClickLabel", "Switch To Tab2"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_1), _translate("ClickLabel", "Tab 1"))
        self.t2_text_label.setText(_translate("ClickLabel", "这里是tab2"))
        self.t2_switch_t1_label.setText(_translate("ClickLabel", "Switch To Tab1"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_2), _translate("ClickLabel", "Tab 2"))
