# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(750, 515)
        self.background = QtWidgets.QWidget(main)
        self.background.setStyleSheet("QWidget#background{\n"
"background-image:url(:/bg/resource/draw/bg.jpg);\n"
"background-repeat:no-repeat;\n"
"background-position:center;}\n"
"")
        self.background.setObjectName("background")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.global_tab = QtWidgets.QTabWidget(self.background)
        self.global_tab.setStyleSheet("QTabWidget::pane {\n"
"    border-top: 2px solid rgba(0, 0, 0, 1); /* 黑色 */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 15px;\n"
"    font-weight: Normal;\n"
"    padding: 10px 25px; /* 调整内边距 */\n"
"    border-bottom: none;\n"
"    min-width: 45px;\n"
"    min-height: 25px; /* 增加最小高度以确保文本显示完整 */\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: white; /* 白色 */\n"
"    border-bottom: 2px solid rgb(101, 108, 137); /* 淡蓝色 */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-bottom: 2px;\n"
"}\n"
"")
        self.global_tab.setObjectName("global_tab")
        self.start_page = QtWidgets.QWidget()
        self.start_page.setObjectName("start_page")
        self.global_tab.addTab(self.start_page, "")
        self.display_page = QtWidgets.QWidget()
        self.display_page.setObjectName("display_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.display_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.function_page = QtWidgets.QWidget(self.display_page)
        self.function_page.setObjectName("function_page")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.function_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.function_path_page = QtWidgets.QWidget(self.function_page)
        self.function_path_page.setObjectName("function_path_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.function_path_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.function_tabs = QtWidgets.QTabWidget(self.function_path_page)
        self.function_tabs.setStyleSheet("QTabWidget::pane {\n"
"    border-top: 1px solid rgba(0, 0, 0, 1); /* 黑色 */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 10px;\n"
"    font-weight: 500;\n"
"    padding: 10px 25px; /* 增加内边距 */\n"
"    border-bottom: none;\n"
"    min-width: 30px;\n"
"    min-height: 18px\n"
"   \n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: white; /* 淡蓝色 */\n"
"    border-bottom: 1px solid rgb(101,108,137); /* 淡蓝色 */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-bottom: 2px;\n"
"}\n"
"")
        self.function_tabs.setObjectName("function_tabs")
        self.function_1 = QtWidgets.QWidget()
        self.function_1.setObjectName("function_1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.function_1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.func1_llm_page = QtWidgets.QWidget(self.function_1)
        self.func1_llm_page.setObjectName("func1_llm_page")
        self.horizontalLayout_3.addWidget(self.func1_llm_page)
        self.plot_page_func_2 = QtWidgets.QWidget(self.function_1)
        self.plot_page_func_2.setObjectName("plot_page_func_2")
        self.horizontalLayout_3.addWidget(self.plot_page_func_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 3)
        self.function_tabs.addTab(self.function_1, "")
        self.function_2 = QtWidgets.QWidget()
        self.function_2.setObjectName("function_2")
        self.function_tabs.addTab(self.function_2, "")
        self.verticalLayout_3.addWidget(self.function_tabs)
        self.path_selector_page = QtWidgets.QWidget(self.function_path_page)
        self.path_selector_page.setStyleSheet("background-color:rgb(235, 235, 235)")
        self.path_selector_page.setObjectName("path_selector_page")
        self.verticalLayout_3.addWidget(self.path_selector_page)
        self.verticalLayout_3.setStretch(0, 8)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.function_path_page)
        self.function_tools = QtWidgets.QWidget(self.function_page)
        self.function_tools.setStyleSheet("background-color:rgb(235, 235, 235)")
        self.function_tools.setObjectName("function_tools")
        self.horizontalLayout.addWidget(self.function_tools)
        self.horizontalLayout.setStretch(0, 15)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.function_page)
        self.global_tab.addTab(self.display_page, "")
        self.horizontalLayout_2.addWidget(self.global_tab)
        self.tools = QtWidgets.QWidget(self.background)
        self.tools.setObjectName("tools")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tools)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tools_global = QtWidgets.QWidget(self.tools)
        self.tools_global.setObjectName("tools_global")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tools_global)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.close_button = QtWidgets.QPushButton(self.tools_global)
        self.close_button.setStyleSheet("QPushButton{\n"
"\n"
"   background-color: transparent;\n"
"}\n"
"QPushButton:hover{\n"
"   icon:url(:/icon/resource/apl/close_selected.png)\n"
"}\n"
"QPushButton:pressed{\n"
"   icon:url(:/icon/resource/apl/close_light.png)\n"
"}\n"
"")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resource/apl/close_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setObjectName("close_button")
        self.verticalLayout_4.addWidget(self.close_button)
        self.verticalLayout.addWidget(self.tools_global)
        spacerItem = QtWidgets.QSpacerItem(20, 470, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        self.horizontalLayout_2.addWidget(self.tools)
        self.horizontalLayout_2.setStretch(0, 13)
        self.horizontalLayout_2.setStretch(1, 1)
        main.setCentralWidget(self.background)

        self.retranslateUi(main)
        self.global_tab.setCurrentIndex(1)
        self.function_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainWindow"))
        self.global_tab.setTabText(self.global_tab.indexOf(self.start_page), _translate("main", "开始"))
        self.function_tabs.setTabText(self.function_tabs.indexOf(self.function_1), _translate("main", "chapter1"))
        self.function_tabs.setTabText(self.function_tabs.indexOf(self.function_2), _translate("main", "chapter2"))
        self.global_tab.setTabText(self.global_tab.indexOf(self.display_page), _translate("main", "功能"))
import resource_rc
