# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\wechat_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chat_Message(object):
    def setupUi(self, Chat_Message):
        Chat_Message.setObjectName("Chat_Message")
        Chat_Message.resize(599, 99)
        self.verticalLayout = QtWidgets.QVBoxLayout(Chat_Message)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QWidget(Chat_Message)
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.avatar_layout = QtWidgets.QWidget(self.main)
        self.avatar_layout.setObjectName("avatar_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.avatar_layout)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.avatar_w = QtWidgets.QWidget(self.avatar_layout)
        self.avatar_w.setMinimumSize(QtCore.QSize(30, 30))
        self.avatar_w.setMaximumSize(QtCore.QSize(30, 30))
        self.avatar_w.setStyleSheet("image: url(:/resources/avatar12.png);\n"
"border-radius: 11px;\n"
"margin:4px;\n"
"background-color: rgba(214, 214, 214, 200);")
        self.avatar_w.setObjectName("avatar_w")
        self.horizontalLayout.addWidget(self.avatar_w)
        self.avatar_name_label = QtWidgets.QLabel(self.avatar_layout)
        self.avatar_name_label.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.avatar_name_label.setObjectName("avatar_name_label")
        self.horizontalLayout.addWidget(self.avatar_name_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.avatar_layout)
        self.message_widget = QtWidgets.QWidget(self.main)
        self.message_widget.setObjectName("message_widget")
        self.verticalLayout_2.addWidget(self.message_widget)
        self.time_layout = QtWidgets.QWidget(self.main)
        self.time_layout.setObjectName("time_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.time_layout)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.time_space_w = QtWidgets.QWidget(self.time_layout)
        self.time_space_w.setMinimumSize(QtCore.QSize(48, 0))
        self.time_space_w.setMaximumSize(QtCore.QSize(48, 9999))
        self.time_space_w.setStyleSheet("")
        self.time_space_w.setObjectName("time_space_w")
        self.horizontalLayout_3.addWidget(self.time_space_w)
        self.time_label = QtWidgets.QLabel(self.time_layout)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(6)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color: rgb(148, 148, 148);")
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_3.addWidget(self.time_label)
        self.verticalLayout_2.addWidget(self.time_layout)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 5)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout.addWidget(self.main)

        self.retranslateUi(Chat_Message)
        QtCore.QMetaObject.connectSlotsByName(Chat_Message)

    def retranslateUi(self, Chat_Message):
        _translate = QtCore.QCoreApplication.translate
        Chat_Message.setWindowTitle(_translate("Chat_Message", "Form"))
        self.avatar_name_label.setText(_translate("Chat_Message", "Maud Carson"))
        self.time_label.setText(_translate("Chat_Message", "3:10PM"))
