# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/chat_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Chat_Main(object):
    def setupUi(self, Chat_Main):
        Chat_Main.setObjectName("Chat_Main")
        Chat_Main.resize(1002, 655)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Chat_Main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message_placeholder = QtWidgets.QWidget(Chat_Main)
        self.message_placeholder.setObjectName("message_placeholder")
        self.verticalLayout_2.addWidget(self.message_placeholder)
        self.input_frame = QtWidgets.QFrame(Chat_Main)
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.input_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.input_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.scroll_pre_button = QtWidgets.QPushButton(self.input_frame)
        self.scroll_pre_button.setObjectName("scroll_pre_button")
        self.horizontalLayout.addWidget(self.scroll_pre_button)
        self.scroll_next_button = QtWidgets.QPushButton(self.input_frame)
        self.scroll_next_button.setObjectName("scroll_next_button")
        self.horizontalLayout.addWidget(self.scroll_next_button)
        self.verticalLayout_2.addWidget(self.input_frame)

        self.retranslateUi(Chat_Main)
        QtCore.QMetaObject.connectSlotsByName(Chat_Main)

    def retranslateUi(self, Chat_Main):
        _translate = QtCore.QCoreApplication.translate
        Chat_Main.setWindowTitle(_translate("Chat_Main", "Chat"))
        self.scroll_pre_button.setText(_translate("Chat_Main", "Previous"))
        self.scroll_next_button.setText(_translate("Chat_Main", "Next"))
